# Generated by Django 3.2.13 on 2022-08-07 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='app.projecttype'),
        ),
    ]
