# Generated by Django 4.1 on 2022-08-07 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220807_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='app.projecttype', to_field='title'),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='title',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
