# Generated by Django 3.2.13 on 2022-08-07 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_portfolio_project_type_alter_projecttype_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.projecttype', to_field='title'),
        ),
    ]
