# Generated by Django 3.2.13 on 2022-08-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_portfolio_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='images/portfolio/project-design')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_design',
            field=models.ManyToManyField(to='app.ProjectDesign'),
        ),
    ]
