# Generated by Django 4.1 on 2022-08-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220807_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatOurClientsSay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('image', models.FileField(blank=True, upload_to='images/what-our-clients-say')),
                ('username', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
