# Generated by Django 4.1 on 2022-08-13 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=50)),
                ('about_project', models.TextField(default='')),
                ('file', models.FileField(blank=True, upload_to='project-files/price-offer')),
                ('firstname', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('project_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.projecttype', to_field='title')),
            ],
        ),
    ]
