# Generated by Django 4.1 on 2022-08-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_scheduleacall'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdesign',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
