# Generated by Django 3.2.13 on 2022-09-11 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_ourwork'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='brief',
            new_name='brief_armenian',
        ),
        migrations.RenameField(
            model_name='projecttype',
            old_name='title',
            new_name='title_armenian',
        ),
        migrations.RenameField(
            model_name='whatourclientssay',
            old_name='description',
            new_name='description_armenian',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='project_type',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='brief_english',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='brief_russian',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_type_english',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.projecttype', to_field='title_english'),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='title_english',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='title_russian',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='whatourclientssay',
            name='description_english',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='whatourclientssay',
            name='description_russian',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='priceoffer',
            name='project_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.projecttype', to_field='title_english'),
        ),
        migrations.AlterField(
            model_name='scheduleacall',
            name='project_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.projecttype', to_field='title_english'),
        ),
    ]
